% Auto-generated by cameraCalibrator app on 07-Jun-2025
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration2.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration3.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration4.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration5.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration6.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration7.png',...
    'C:\Users\Rebel Author\Documents\MATLAB\scaryproject\calibration\calibration8.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
minCornerMetric = 0.150000;
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'MinCornerMetric', minCornerMetric);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 22.000000;  % in millimeters
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% % View reprojection errors
% h1=figure; showReprojectionErrors(cameraParams);
% 
% % Visualize pattern locations
% h2=figure; showExtrinsics(cameraParams, 'CameraCentric');
% 
% % Display parameter estimation errors
% displayErrors(estimationErrors, cameraParams);
% 
% % For example, you can use the calibration data to remove effects of lens distortion.
% undistortedImage = undistortImage(originalImage, cameraParams);
% 
% % See additional examples of how to use the calibration data.  At the prompt type:
% % showdemo('MeasuringPlanarObjectsExample')
% % showdemo('StructureFromMotionExample')
